# docker-compose.yaml
services:
  backend:
    # for dev: builds from your local Dockerfile.backend
    # for prod: uncomment the next line and comment out the build: block
    # image: vandadvafai/resume_evaluator-backend:latest

    build:
      context: .
      dockerfile: Dockerfile.backend
    image: vandadvafai/resume_evaluator-backend:latest

    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    # for dev: builds from your local Dockerfile.frontend
    # for prod: uncomment the next line and comment out the build: block
    # image: vandadvafai/resume_evaluator-frontend:latest

    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: vandadvafai/resume_evaluator-frontend:latest

    environment:
      # point React at your backend service; React picks this up via process.env.REACT_APP_API_URL
      - REACT_APP_API_URL=http://backend:8000
    ports:
      - "3000:80"    # maps host port 3000 → container port 80 (nginx)
    depends_on:
      backend:
        condition: service_healthy
